---
- name: posix test
  hosts: localhost
  gather_facts: true

  - name: test a posix thingy
    ansible.posix.selinux:
      state: diabled

  - name: show me the money
    shell: getenforce
    register: enforce

  - name: show data
    msg: {{ enforce }}
